AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  asynchronusLambdaFunction

  Sample SAM Template for asynchronusLambdaFunction

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    MemorySize: 128

Resources:
  checkoutbatientbucketlist:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:  !Sub ${AWS::StackName}-${AWS::AccountId}-${AWS::Region}
  Patientcheckouttopic:
    Tyoe: AWS:SNS::Topic
  PatientCheckoutFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: patientcheckout
      Handler: com.conroy.aws.lambda.s3sns.PatientCheckoutLambda::handler
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Policies:
        - S3ReadPolicy:
            BucketName: !Sub ${AWS::StackName}-${AWS::AccountId}-${AWS::Region}
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt Patientcheckouttopic.TopicName
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PATIENT_CHECKOUT_TOPIC: !Ref Patientcheckouttopic
          PARAM1: VALUE
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 # More info about tiered compilation https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/
      Events:
        S3Event:
          Type: S3 # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Bucket:  !Ref checkoutbatientbucketlist
            Events: s3:ObjectCreated:*
  PatientBuildManagementFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: patientcheckout
      Handler: com.conroy.aws.lambda.s3sns.BuildManagementLambda::handler
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Events:
        SNSEvent:
          Type: SNS # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Topic:  !Ref Patientcheckouttopic        
